# Generated by Django 5.1.5 on 2025-01-18 07:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0002_remove_exam_duration_remove_exam_passing_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='app_course.exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.DurationField(default=1, verbose_name=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='passing_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
