# Generated by Django 5.1.5 on 2025-01-21 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0003_alter_assignment_course_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritecourse',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_course.favourite'),
        ),
        migrations.AlterField(
            model_name='favouritecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_course', to='app_course.course'),
        ),
    ]
