# Generated by Django 5.1.5 on 2025-01-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0005_chat_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='parent_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_course.review'),
        ),
    ]
